package com.legacy.aether.client.renders.entity;

import net.minecraft.client.renderer.entity.Render;
import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;

public class WhirlwindRenderer extends Render {

    public WhirlwindRenderer() {
        super();
    }

    @Override
    public void doRender(Entity entity, double renderX, double renderY, double renderZ, float p_76986_8_, float p_76986_9_) {

    }

    @Override
    protected ResourceLocation getEntityTexture(Entity entity) {
        return null;
    }

}